version: "3"

services:
  carmelofiorello:
    container_name: carmelofiorello
    image: ghcr.io/dj-fiorex/carmelofiorello.com:latest
    #ports: We don't need to expose the port because we are using the traefik
    #  - '3000:3000'
    networks:
      - traefik

    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.carmelofiorello.loadbalancer.server.port=3000"
      - "traefik.http.routers.carmelofiorello.rule=Host(`carmelofiorello.com`)"
      - "traefik.http.routers.carmelofiorello.entrypoints=websecure"
      - "traefik.http.routers.carmelofiorello.tls.certresolver=letsencryptresolver"

networks:
  traefik:
    external: true
